development:
  adapter: mysql2
  database: railsdev_social_networking
  usename: railsdev_sachin
  password: railsdev_sachin
  host: 64.62.143.85
test:
  adapter: mysql2
  database: social_networking_test
  username: root
  password:

production:
  adapter: mysql2
  database: railsdev_social_networking
  usename: railsdev_sachin
  password: railsdev_sachin
  host: 64.62.143.85